Traceability interop
w3c/cg-reports pull request #53
Opened 2024-12-04 17:14 UTC by mkhraisha

Adds Traceability Interop spec following procedure in the readme

2024-12-04 17:30 UTC, dontcallmedom requested changes
* the fileame should be index.html rather than `unofficial-…`
* the `CG-FINAL-traceability…` directory should be part of the `credentials` directory (since this is report from the credentials CG)
* the "latest published version" URI is wrong
* conversely, you may want to set a "This version" URI

2024-12-04 19:20 UTC, mkhraisha commented
@dontcallmedom
Updated filename,
Moved to credentials,
Updated URL for latest version I used https://www.w3.org/community/reports/ccg/CG-FINAL-traceability-interop-20241204 as i believe that is where it will end up but please let me know if im supposed to do anything else

2024-12-05 05:40 UTC, dontcallmedom commented on credentials/CG-FINAL-traceability-interop-20241204/index.html
> +<link rel="canonical" href="https://www.w3.org/community/reports/ccg/CG-FINAL-traceability-interop-20241204">
```suggestion
<link rel="canonical" href="https://www.w3.org/community/reports/credentials/CG-FINAL-traceability-interop-20241204">
```

2024-12-05 05:40 UTC, dontcallmedom commented on credentials/CG-FINAL-traceability-interop-20241204/index.html
> +              <a href="https://www.w3.org/community/reports/ccg/CG-FINAL-traceability-interop-20241204">https://www.w3.org/community/reports/ccg/CG-FINAL-traceability-interop-20241204</a>
```suggestion
              <a href="https://www.w3.org/community/reports/credentials/CG-FINAL-traceability-interop-20241204">https://www.w3.org/community/reports/credentials/CG-FINAL-traceability-interop-20241204</a>
```

2024-12-05 17:06 UTC, dontcallmedom approved these changes

2024-12-05 17:06 UTC, merged